name: Test against supported .NET

on:
  - workflow_call


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Start RabbitMQ
        id: start-rabbitmq
        run: ${{ github.workspace }}/.ci/ubuntu/gha-setup.sh toxiproxy
      - name: Build (Debug)
        run: dotnet build ${{ github.workspace }}/Build.csproj
      - name: Verify
        run: dotnet format ${{ github.workspace }}/Build.csproj --no-restore --verify-no-changes
      - name: Test
        run: dotnet test ${{ github.workspace }}/Build.csproj --no-restore --no-build --logger "console;verbosity=detailed" /p:AltCover=true
      - name: Check for errors in RabbitMQ logs
        run: ${{ github.workspace}}/.ci/ubuntu/gha-log-check.sh
      - name: Maybe collect toxiproxy logs
        if: failure()
        run: docker logs rabbitmq-amqp-dotnet-client-toxiproxy > ${{ github.workspace }}/.ci/ubuntu/log/toxiproxy.log
      - name: Maybe upload RabbitMQ logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: rabbitmq-logs-integration-ubuntu
          path: ${{ github.workspace }}/.ci/ubuntu/log/
